apiVersion: apps/v1
kind: Deployment
metadata:
  name: akrobateo
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: akrobateo
  template:
    metadata:
      labels:
        name: akrobateo
    spec:
      serviceAccountName: akrobateo
      containers:
        - name: akrobateo
          image: ghcr.io/alexfouche/akrobateo:0.1.1.20220907_1542.6552878
          # image: lukasauerbeck/akrobateo-mirror:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 20M
              cpu: 100m
            limits:
              memory: 100M
              cpu: 200m
          env:
            - name: LB_IMAGE
              value: ghcr.io/alexfouche/akrobateo-lb:0.1.1.20220907_1542.6552878
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "akrobateo"
